In [2]:
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
import joblib

In [3]:
class Node():
    def __init__(self, features = None, threshold = None, left = None, right = None,*, value = None):
        self.features = features
        self.threshold = threshold
        self.left = left
        self.right = right
        self.value = value
    
    def _is_leaf_node(self):
        return self.value is not None
    
class _Decision_Tree_():
    def __init__(self, min_sample_split = 3, max_depth = 200, n_features = None):
        self.min_sample_split = min_sample_split
        self.max_depth = max_depth
        self.n_features = n_features
        self.roots = None

    def fit(self, x,y):
        self.n_features = x.shape[1] if not self.n_features else min(x.shape[1], self.n_features)
        self.root = self._grow_tree_(x,y)
    
    def _grow_tree_(self,x,y,depth = 0):
        n_samples, n_feature = x.shape
        n_labels = len(np.unique(y))

        # stopping condition
        if (depth >= self.max_depth or n_labels == 1 or n_samples < self.min_sample_split):
            leaf_value = self.most_common_value(y)
            return Node(value = leaf_value)
        
        feats = np.random.choice(n_feature, self.n_features, replace=False)
        best_features, best_threshold = self._best_split_(x,y,feats)

        left_idxs, right_idxs = self._split_(x[:, best_features], best_threshold)
        left = self._grow_tree_(x[left_idxs,:], y[left_idxs], depth+1)
        right = self._grow_tree_(x[right_idxs,:], y[right_idxs], depth+1)

        return Node(best_features, best_threshold, left, right)

    def most_common_value(self,y):
        #y=np.ravel(y)
        counter = Counter(y)
        common_value = counter.most_common(1)[0][0]
        return common_value
    
    def _best_split_(self,x,y, n_feats):
        best_gain = -1
        split_idxs, split_threshold = None, None

        for idxs in n_feats:
            x_column = x[:,idxs]
            threshold = np.unique(x_column)

            for thr in threshold:
                gain = self._information_gain_(x_column,y,thr)

                if gain > best_gain:
                    best_gain = gain
                    split_idxs = idxs
                    split_threshold = thr
            
        return split_idxs, split_threshold

    def _information_gain_(self,x,y,thrs):
        parent_entropy = self._entropy_(y)

        left_idxs, right_idxs = self._split_(x,thrs)

        if len(left_idxs) == 0 or len(right_idxs) == 0 :
            return 0
        
        n = len(y)
        n_l, n_r = len(left_idxs), len(right_idxs)
        e_l, e_r = self._entropy_(y[left_idxs]), self._entropy_(y[right_idxs])

        child_entropy = (n_l/n)*e_l + (n_r/n)*e_r

        info = parent_entropy - child_entropy
        return info

    def _entropy_(self,y):
        #y = y.ravel()
        hist = np.bincount(y)
        ps = hist/len(y)
        ent = -np.sum([p*np.log(p) for p in ps if p>0])
        return ent
    
    def _split_(self, x,thrsh):
        left = np.argwhere(x <= thrsh).flatten()
        right = np.argwhere(x > thrsh).flatten()
        return left, right
    
    def predict(self,x):
        pred = self._traverse_tree_(x, self.root)
        return pred
    
    def _traverse_tree_(self, x, node):
        if node._is_leaf_node(): 
            return [1.0 if node.value == 0 else 0.0, 1.0 if node.value == 1 else 0.0]
        
        if x[node.features] <= node.threshold:
            return self._traverse_tree_(x,node.left)
        return self._traverse_tree_(x, node.right)

In [4]:
class Random_forest():
    def __init__(self, min_sample_split = 2, max_depth = 10, n_trees = 20, n_features = None):
        self.n_features = n_features
        self.min_sample_split = min_sample_split
        self.max_depth = max_depth
        self.n_trees =n_trees
        self.trees = []

    def fit(self,x,y):
        self.trees = []
        for _ in range(self.n_trees):
            tree = _Decision_Tree_(min_sample_split = self.min_sample_split, max_depth = self.max_depth, n_features = self.n_features)

            x_sample, y_sample = self.bootstrap(x,y)
            tree.fit(x_sample,y_sample)
            self.trees.append(tree)

    def bootstrap(self,x,y):
        n_samples = x.shape[0]
        idxs = np.random.choice(n_samples, n_samples, replace= True)
        return x[idxs], y[idxs]

    def predict(self,x):
        tree_probs = np.array([tree.predict(xi) for tree in self.trees for xi in x])
        tree_probs = tree_probs.reshape(len(self.trees), len(x),2)
        avg_predictions = np.mean(tree_probs, axis=0)
        return avg_predictions

    def most_common_value(self,y):
        counter = Counter(y)
        commo = counter.most_common(1)[0][0]
        return commo

In [15]:
import pandas as pd

df = pd.read_csv('diabetes.csv')
cols = df.columns

In [16]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
# for col in cols:
#     df[col] = (df[col] - df[col].min())/(df[col].max() - df[col].min())

In [17]:
for col in cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3-q1
    lower_bound = q1-iqr*1.5
    upper_bound = q3+iqr*1.5

    df[col] = df[col].apply(lambda x : lower_bound if x<lower_bound else upper_bound if x>upper_bound else x)

In [18]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1
1,1.0,85.0,66.0,29.0,0.0,26.6,0.351,31.0,0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0
4,0.0,137.0,40.0,35.0,168.0,43.1,1.200,33.0,1
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0
764,2.0,122.0,70.0,27.0,0.0,36.8,0.340,27.0,0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0
766,1.0,126.0,60.0,0.0,0.0,30.1,0.349,47.0,1
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0

In [19]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [20]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1:].values

In [21]:
y = y.astype(int)
y = y.flatten()

In [22]:
clf = Random_forest()
clf.fit(x,y)

In [23]:
joblib.dump(clf, 'diabetes_model.pkl')

['diabetes_model.pkl']